CREATE DOMAIN cart_item_id  AS INTEGER CHECK (VALUE > 0);
CREATE DOMAIN quantity      AS INTEGER CHECK (VALUE > 0);
CREATE DOMAIN user_id       AS INTEGER CHECK (VALUE > 0);
CREATE DOMAIN store_id      AS INTEGER CHECK (VALUE > 0);
CREATE DOMAIN product_id    AS INTEGER CHECK (VALUE > 0);
CREATE DOMAIN warehouse_id  AS UUID;
CREATE DOMAIN order_id      AS UUID;
CREATE DOMAIN order_slug    AS INTEGER CHECK (VALUE > 0);
CREATE DOMAIN order_diff_id AS UUID;
