ALTER TABLE cart_items
    ALTER COLUMN id TYPE INTEGER,
    ALTER COLUMN user_id TYPE INTEGER,
    ALTER COLUMN product_id TYPE INTEGER,
    ALTER COLUMN store_id TYPE INTEGER,
    ALTER COLUMN store_id SET DEFAULT -1,
    ALTER COLUMN quantity TYPE INTEGER;
