[listen]
host = "0.0.0.0"
port = 8000
[db]
dsn = "postgresql://orders:orders@orders-pg/orders"
[graylog]
addr = "udplog.stq.cloud:32303"
[delivered_orders]
interval_s = 86400
delivery_state_duration_days = 15
