[listen]
host = "0.0.0.0"
port = 8000

[db]
dsn = "postgresql://orders:orders@orders-pg/orders"

[delivered_orders]
interval_s = 86400 #24 hours
delivery_state_duration_days = 14
saga_url="http://saga:8000"

[sent_orders]
interval_s = 86400 #24 hours
sent_state_duration_days = 14
ups_api_access_license_number = "Your licence number goes here"
ups_api_url = "https://wwwcie.ups.com/rest/Track"

[paid_delivered_report]
interval_s = 21600 #6 hours

[s3]
region = "us-east-1"
bucket = "storiqa-dev"
key = "AKIAJTQ4IR33MOO6VS2Q"
secret = "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"
acl = "public-read"
